### ISSUE TITLE
Why is the 0 score so low? Spectre toy example

### ISSUE THREAD

**Issue by Flockenmumie** [msmania/microarchitectural-attack#2]
Hi! Thank you for providing this code! I was wondering, why the PoC #2: Toy example of Spectre always shows a very low score at 0 when using variant 1. (27 in your example). It is not the case at the Toy example of Meltdown. Does it hast to do something with int idx_min = 1 and what does it mean?
Many thanks in advance!

**Comment by msmania** [comment]
Hi! Thank you for trying my code, and sorry for not responding timely.

It's really a good question and thank you for bringing it up.  Yes, [`idx_min = 1`](https://github.com/msmania/microarchitectural-attack/blob/v1.0/02_spectre_toy/main.cpp#L45) means I wanted to skip measuring `tat[0]` because it's false-positive.

A low score of `tat[0]` is a side effect from calling `branch_predictor` with `x = 0`.  When x is 0, `branch_predictor` runs all instructions normally (without any speculation), and it touches `probe[0]`.  If you change the value of [`gateway`](https://github.com/msmania/microarchitectural-attack/blob/v1.0/02_spectre_toy/main.cpp#L26) to 1 or some other value, you can see the position of this side-effect moves to somewhere.

If there is anything unclear, please let me know.  I'm happy to answer!
